version: '3.9'

services:
  #new service (stc_app)
  stc_app:
    container_name: stc_app
    image: mohamedadellotfy/stc_app:1.0.0
    build: .
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:postgresql://stc_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - stc_db

  #old service (postgres)
  stc_db:
    container_name: stc_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stc
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}